### ISSUE TITLE
semantic predicate used in rule is called before :around function

### ISSUE THREAD

**Issue by cellux** [scymtym/esrap#9]
```lisp
(defvar *around-test*)

(defun check (x)
  (push :checking *around-test*)
  x)

(defrule around-test
    (check "bravo")
  (:around ()
    (let* ((*around-test* nil)
           (result (esrap:call-transform)))
      (assert (equal '(:checking) *around-test*))
      result)))

(assert (equal "bravo" (parse 'around-test "bravo")))
```

The parse call errors out with `The variable *AROUND-TEST* is unbound.`

I expected that the the :around expression wraps around the rule execution - i.e. the call `(check "bravo")` is not made until I call `(esrap:call-transform)` inside the :around expression.

**Comment by scymtym** [comment]
The `:around` clause of `defrule` is part of computing the production of the rule which happens only after a successful complete parse as well as lazily.

Semantic predicates, on the other hand, must be evaluated to decide whether the parse is successful or not.

In your example, the rule expression `(check "bravo")` is thus evaluated (long) before the `:around` clause and `*around-test*` is unbound at that time.

There is a way to interleave the computation of rule productions and thus `:around` clauses with expression evaluation: since semantic predicates look at the production of an expression, that production has to be computed while parsing. A way to exploit this is:

```cl
(defun force-helper (x)
  x)

(defrule force-around
  (force-helper around-rule))

(defrule around-rule
    EXPRESSION
  (:around ()
    …))
```

In this example, the `:around` clause of `around-rule` will be executed immediately before `force-helper` is called in `force-around`. But note that the `:around` clause cannot establish bindings or other things for the dynamic scope of the `(esrap:call-transform)` call to affect the evaluation of `EXPRESSION`.

**Comment by cellux** [comment]
Thanks for the extensive answer.

**Comment by scymtym** [comment]
Please reopen if there are further issues.
